name: Fork Repository and Rsync

on:
  workflow_dispatch:

jobs:
  AospRsync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git gpg rsync repo


      - name: Configure the 'crave' environment
        run: |
         if [[ "${DCDEVSPACE}" == "1" ]]; then
         echo 'No need to set up crave, we are already running in devspace!'
         else
         mkdir ${HOME}/bin/
         curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
          mv ${PWD}/crave ${HOME}/bin/
          sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
          envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
          rm -rf ${PWD}/crave.conf.sample
          fi
        env:
          CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
          CRAVE_TOKEN: ${{  secrets.CRAVE_TOKEN  }}

        
      - name: Rsync and Upload intro repository 
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "zeroXone-github"
          mkdir project
          cd project
          crave -h
          git add .
          git commit -m "Gething repository, rsync and upload it"
          git push origin main
