name: Fork Repository and Rsync

on:
  workflow_dispatch:

jobs:
  AospRsync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git gpg rsync
      - name: Rsync and Upload intro repository 
        run: |
          neofetch
          git config --global user.email "you@example.com"
          git config --global user.name "zeroXone-github"
          repo init -u https://github.com/PixelOS-AOSP/manifest.git -b fifteen
          repo sync
          git add .
          git commit -m "Gething repository, rsync and upload it"
          git push origin main
